#Requires -Version 5.1
<#
.SYNOPSIS
  Write a user-level Cargo config for Windows MSVC builds (not committed to git).

.DESCRIPTION
  Creates/merges settings into %USERPROFILE%\.cargo\config.toml:
  rust-lld linker, large stack, debuginfo=0, PROTOC env.

.EXAMPLE
  .\script\windows\install-cargo-config.ps1
  .\script\windows\install-cargo-config.ps1 -Force
#>
[CmdletBinding()]
param(
    [string]$ProtocVersion = '29.3',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$cargoDir = Join-Path $env:USERPROFILE '.cargo'
$configPath = Join-Path $cargoDir 'config.toml'
$protocExe = Join-Path $env:LOCALAPPDATA "protoc-$ProtocVersion\bin\protoc.exe"
$protocToml = $protocExe.Replace('\', '\\')

if (-not (Test-Path -LiteralPath $protocExe)) {
    Write-Warning "protoc not found at $protocExe — run install-protoc.ps1 first."
}

New-Item -ItemType Directory -Force -Path $cargoDir | Out-Null

$block = @"
# Generated by grok-build script/windows/install-cargo-config.ps1
# Local only — do not commit this file to the repo.

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = [
  "-C", "force-unwind-tables=yes",
  "-C", "target-feature=+crt-static",
  "-C", "debuginfo=0",
  "-C", "link-arg=/STACK:16777216",
]

[env]
PROTOC = { value = "$protocToml", force = true }
"@

if ((Test-Path -LiteralPath $configPath) -and -not $Force) {
    $existing = Get-Content -LiteralPath $configPath -Raw
    if ($existing -match 'x86_64-pc-windows-msvc' -and $existing -match 'rust-lld') {
        Write-Host "Config already looks configured: $configPath"
        Write-Host "Re-run with -Force to overwrite the Windows block (backs up existing file)."
        exit 0
    }
    $backup = "$configPath.bak-$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -LiteralPath $configPath -Destination $backup
    Write-Host "Backed up existing config to $backup"
    Add-Content -LiteralPath $configPath -Value "`n$block"
    Write-Host "Appended Windows settings to $configPath"
} else {
    if (Test-Path -LiteralPath $configPath) {
        $backup = "$configPath.bak-$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item -LiteralPath $configPath -Destination $backup
        Write-Host "Backed up existing config to $backup"
    }
    Set-Content -LiteralPath $configPath -Value $block -Encoding utf8
    Write-Host "Wrote $configPath"
}

Write-Host "You can now run: cargo build -p xai-grok-pager-bin"
